# Generated by Django 4.1.3 on 2023-01-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
            ],
        ),
    ]
