# Generated by Django 4.1.3 on 2023-01-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('InComplete', 'InComplete')], default='InComplete', max_length=200),
        ),
    ]
