# Generated by Django 4.2 on 2023-04-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_pages_read_alter_book_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
